version: 2

formats:
  - pdf

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .
  system_packages: true
